import React from "react";
import {
  MdDashboard,
  MdInventory,
  MdAttachMoney,
  MdShoppingCart,
  MdReport,
  MdSettings,
  MdLogout,
} from "react-icons/md";
import { useNavigate } from "react-router-dom";

//Endpoints for API calls
export const API_BASE_URL = "http://localhost:5001/api";

//sidebar// sidebarConfig.js
// sidebarConfig.js

export const panelActions = {
  Finance: [
    { label: "New Journal Entry", path: "/home/finance/journal-entry" },
    { label: "Add Account", path: "/home/finance/accounts/new" },
  ],
  Inventory: [{ label: "Add Inventory Item", path: "/home/inventory/add" }],

  Purchases: [{ label: "New Request", path: "/home/purchases/create_request" }],
};

export const sidebarConfig = [
  {
    label: "Dashboard",
    icon: <MdDashboard />,
    path: "/home/dashboard",
  },
  {
    label: "Inventory",
    icon: <MdInventory />,
    submenu: {
      Profiles: [
        { label: "Master Financial Calendar", path: "/home/finance/calendar" },
        { label: "Recurring Transactions", path: "/home/finance/recurring" },
        { label: "Chart of Accounts", path: "/home/finance/accounts" },
        { label: "Subaccounts", path: "/home/finance/subaccounts" },
      ],
      Processes: [
        { label: "Manage Financial Periods", path: "/home/finance/periods" },
        { label: "Validate Account History", path: "/home/finance/history" },
      ],
      Budgets: [
        { label: "Budgets", path: "/home/finance/budgets" },
        { label: "GL Budget Edit", path: "/home/finance/budget-edit" },
      ],
      Inquiries: [
        { label: "Account Summary", path: "/home/finance/summary" },
        { label: "Account by Subaccount", path: "/home/finance/by-subaccount" },
        { label: "Account by Period", path: "/home/finance/by-period" },
        { label: "Account Details", path: "/home/finance/details" },
      ],
      Preferences: [
        { label: "General Ledger Preferences", path: "/home/finance/gl-prefs" },
        { label: "Financial Year", path: "/home/finance/year" },
        { label: "Ledgers", path: "/home/finance/ledgers" },
        { label: "Voucher Entry Codes", path: "/home/finance/vouchers" },
        { label: "Budget Configuration", path: "/home/finance/budget-config" },
        { label: "Consolidation", path: "/home/finance/consolidation" },
        { label: "Account Classes", path: "/home/finance/classes" },
      ],
    },
  },
  {
    label: "Finance",
    icon: <MdAttachMoney />,
    submenu: {
      Profiles: [
        { label: "Master Financial Calendar", path: "/home/finance/calendar" },
        { label: "Recurring Transactions", path: "/home/finance/recurring" },
        { label: "Chart of Accounts", path: "/home/finance/accounts" },
        { label: "Subaccounts", path: "/home/finance/subaccounts" },
      ],
      Processes: [
        { label: "Manage Financial Periods", path: "/home/finance/periods" },
        { label: "Validate Account History", path: "/home/finance/history" },
      ],
      Budgets: [
        { label: "Budgets", path: "/home/finance/budgets" },
        { label: "GL Budget Edit", path: "/home/finance/budget-edit" },
      ],
      Inquiries: [
        { label: "Account Summary", path: "/home/finance/summary" },
        { label: "Account by Subaccount", path: "/home/finance/by-subaccount" },
        { label: "Account by Period", path: "/home/finance/by-period" },
        { label: "Account Details", path: "/home/finance/details" },
      ],
      Preferences: [
        { label: "General Ledger Preferences", path: "/home/finance/gl-prefs" },
        { label: "Financial Year", path: "/home/finance/year" },
        { label: "Ledgers", path: "/home/finance/ledgers" },
        { label: "Voucher Entry Codes", path: "/home/finance/vouchers" },
        { label: "Budget Configuration", path: "/home/finance/budget-config" },
        { label: "Consolidation", path: "/home/finance/consolidation" },
        { label: "Account Classes", path: "/home/finance/account_class" },
      ],
    },
  },
  {
    label: "Purchases",
    icon: <MdShoppingCart />,
    submenu: {
      Profiles: [
        { label: "Request", path: "/home/request" },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
        },
      ],
      Inquiries: [{ label: "Vendor Details", path: "/home/purchases/details" }],
    },
  },
  {
    label: "Reports",
    icon: <MdReport />,
    path: "/home/reports",
  },
  {
    label: "Settings",
    icon: <MdSettings />,
    path: "/home/settings",
  },
  {
    label: "Log Out",
    icon: <MdLogout />,
    path: "/logout",
  },
];

export const DUMMY_ITEMS = [
  {
    inventory: "Item001232323",
    itemclass: "MHE-SPR-LND asasdasd",
    subitem: "A1",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 20,
    description: "Paper A4 axsasaassaasdassdasdasdadssdasadasdsasadsadsda",
    uom: "Ream",
    orderQty: 1,
    unitCost: 100,
    extVendorCost: 100,
    vendor: "",
    location: "",
    vendorName: "",
    vendorRef: "",
    vendorDescription: "",
    alternateID: "",
    requiredDate: "2025-06-11",
    promisedDate: "2025-06-11",
    issueStatus: "Open",
  },

  {
    inventory: "Item002",
    itemclass: "MHE-SPR-LND",
    subitem: "B2",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Pen Blue",
    uom: "Box",
    orderQty: 2,
    unitCost: 50,
    extVendorCost: 1200,
    location: "",
    vendor: "",
  },
  {
    inventory: "Item003",
    itemclass: "MHE-SPR-LND",
    subitem: "C3",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Notebook",
    uom: "Piece",
    orderQty: 5,
    unitCost: 20,
    extVendorCost: 1300,
    location: "",
    vendor: "",
  },
  {
    inventory: "Item004",
    itemclass: "MHE-SPR-LND",
    subitem: "C3",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Notebook",
    uom: "Piece",
    orderQty: 5,
    unitCost: 20,
    extVendorCost: 300,
    location: "",
    vendor: "",
  },
];

export const requests = [
  {
    ref: "RS1",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PENETRATING OIL - WD40",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "PENETRATING OIL - WD40PENETRATING OIL - WD40",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "PENETRATING OIL - WD40",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "COTTON RAGS",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RS2",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PM Materials for JIA2 - RC5500 / 1A430954",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item001232323",
        itemclass: "MHE-SPR-LND asasdasd",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 20,
        description: "Paper A4 axsasaassaasdassdasdasdadssdasadasdsasadsadsda",
        uom: "Ream",
        orderQty: 1,
        unitCost: 100,
        extVendorCost: 100,
        vendor: "",
        location: "",
        vendorName: "",
        vendorRef: "",
        vendorDescription: "",
        alternateID: "",
        requiredDate: "2025-06-11",
        promisedDate: "2025-06-11",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RS3",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RS4",
    status: "Closed",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "CONSUMABLES",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Rental of Boomtruck for Supersail Cebu",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },

      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RS5",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Internal Rental for Crystal Cold for R20 C2Y115M01362",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RS6",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RS7",
    status: "Closed",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PM Materials for JIA2 - RC5500 / 1A430954",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "PMM-WD40MTLS",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "PENETRATING OIL - WD40",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RS8",
    status: "Closed",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Consumables for SHIN-ETSU Project",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RS9",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Purchase of Linde for Royal Cargo ADY6113 SN: 20240409V154",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Rental of Truck at ROMBE Project (Pull-out)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RS10",
    status: "Open",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Trucking for the delivery of Visipro to Doxo Polyland",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RS11",
    status: "Closed",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Materials for SHIN-ETSU Project",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RS12",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Purchase of Linde for Royal Cargo ADY6113 SN: 20240409V154",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RS13",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  // You can keep the rest of your request objects the same or add `items` to any of them as needed.
];
