import React from "react";
import { CiCircleMinus, CiCirclePlus } from "react-icons/ci";
import { FaRegStar } from "react-icons/fa";
import { IoStarOutline } from "react-icons/io5";
import {
  MdDashboard,
  MdInventory,
  MdAttachMoney,
  MdShoppingCart,
  MdReport,
  MdSettings,
  MdNoteAdd,
  MdTimer,
} from "react-icons/md";
import { useNavigate } from "react-router-dom";

//Endpoints for API calls
export const API_BASE_URL = "http://localhost:5001/api";

//sidebar// sidebarConfig.js
// sidebarConfig.js

export const panelActions = {
  Finance: [
    { label: "New Journal Entry", path: "/home/finance/journal-entry" },
    { label: "Add Account", path: "/home/finance/accounts/new" },
  ],
  Inventory: [{ label: "Add Inventory Item", path: "/home/inventory/add" }],

  Purchases: [{ label: "New Request", path: "/home/purchases/create_request" }],
};

export const sidebarConfig = [
  {
    label: "Time and Expenses",
    icon: <MdTimer />,
    roles: ["admin", "finance"],
    submenu: {
      // Same submenu structure as "Inventory"
      Tasks: [
        {
          label: "Tasks",
          path: "/home/t&e/tasks/events/tasks",
          roles: ["admin", "finance"],
        },
        {
          label: "Approvals",
          path: "/home/t&e/tasks/events/approvals",
          roles: ["admin", "finance"],
        },
        {
          label: "Events",
          path: "/home/t&e/tasks/events",
          roles: ["admin", "finance"],
        },
      ],
      Email: [
        {
          label: "Incoming",
          path: "/home/t&e/email/incoming",
          roles: ["admin", "finance"],
        },
        {
          label: "Draft",
          path: "/home/t&e/email/recurring",
          roles: ["admin", "finance"],
        },
        {
          label: "Sent",
          path: "/home/t&e/email/sent",
          roles: ["admin", "finance"],
        },
        {
          label: "Outgoing",
          path: "/home/t&e/email/outgoing",
          roles: ["admin", "finance"],
        },
        {
          label: "Deleted",
          path: "/home/t&e/email/deleted",
          roles: ["admin", "finance"],
        },
        {
          label: "Archived",
          path: "/home/t&e/email/archived",
          roles: ["admin", "finance"],
        },
      ],
      "Time Tracking": [
        {
          label: "Employee Time Activities",
          path: "/home/t&e/timetracking/eta",
          roles: ["admin", "finance"],
        },
        {
          label: "Weekly Crew Time Entry",
          path: "/home/t&e/timetracking/wcte",
          roles: ["admin", "finance"],
        },
        {
          label: "Employee Time Cards",
          path: "/home/t&e/timetracking/etc",
          roles: ["admin", "finance"],
        },
        {
          label: "Release Time Activities",
          path: "/home/t&e/timetracking/rta",
          roles: ["admin", "finance"],
        },
        {
          label: "Approve Time Activity Summaries",
          path: "/home/t&e/timetracking/atas",
          roles: ["admin", "finance"],
        },
        {
          label: "Release Time Cards",
          path: "/home/t&e/timetracking/rtc",
          roles: ["admin", "finance"],
        },
      ],
      "Explain Claims": [
        {
          label: "Expense Receipts",
          path: "/home/t&e/explainclaims/expense-receipts",
          roles: ["admin", "finance"],
        },
        {
          label: "Expense Claims",
          path: "/home/t&e/explainclaims/expense-claims",
          roles: ["admin", "finance"],
        },
        {
          label: "Release Expense Claims",
          path: "/home/t&e/explainclaims/release-claims",
          roles: ["admin", "finance"],
        },
        {
          label: "Bill Expense Claims",
          path: "/home/t&e/explainclaims/bill-claims",
          roles: ["admin", "finance"],
        },
      ],
      Inquiries: [
        {
          label: "Activities",
          path: "/home/t&e/inquries/activities",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "All Emails",
          path: "/home/t&e/inquries/emails",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account by Period",
          path: "/home/t&e/inquries/abp",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Search in Files",
          path: "/home/t&e/inquries/search-files",
          roles: ["admin", "finance", "viewer"],
        },
      ],
      Reports: [
        {
          label: "Expense Claim Details",
          path: "/home/t&e/reports/ecd",
          roles: ["admin"],
        },
        {
          label: "Expense Claim Details by Employee",
          path: "/home/t&e/reports/ecd-employee",
          roles: ["admin"],
        },
        {
          label: "Expense Claim Details by Department",
          path: "/home/t&e/reports/ecd-department",
          roles: ["admin"],
        },
      ],
      Preferences: [
        {
          label: "Time & Expense Preferences",
          path: "/home/t&e/preferences/tep",
          roles: ["admin"],
        },
        {
          label: "Earning Types",
          path: "/home/t&e/preferences/earning-types",
          roles: ["admin"],
        },
        {
          label: "Activity Types",
          path: "/home/t&e/preferences/activity-types",
          roles: ["admin"],
        },
      ],
    },
  },
  {
    label: "Finance",
    icon: <MdAttachMoney />,
    roles: ["admin", "finance"],
    submenu: {
      // Same submenu structure as "Inventory"

      Transactions: [
        {
          label: "Journal Transactions",
          path: "/home/finance/transactions/jt",
          roles: ["admin", "finance"],
        },
        {
          label: "Journal Vouchers",
          path: "/home/finance/transactions/jv",
          roles: ["admin", "finance"],
        },
        {
          label: "Trial Balance",
          path: "/home/finance/transactions/tb",
          roles: ["admin", "finance"],
        },
      ],
      Profiles: [
        {
          label: "Master Financial Calendar",
          path: "/home/finance/transactions/calendar",
          roles: ["admin", "finance"],
        },
        {
          label: "Allocations",
          path: "/home/finance/transactions/allocations",
          roles: ["admin", "finance"],
        },
        {
          label: "Recurring Transactions",
          path: "/home/finance/transactions/recurring",
          roles: ["admin", "finance"],
        },
        {
          label: "Chart of Accounts",
          path: "/home/finance/transactions/accounts",
          roles: ["admin", "finance"],
        },
        {
          label: "Subaccounts",
          path: "/home/finance/transactions/subaccounts",
          roles: ["admin", "finance"],
        },
      ],
      Processes: [
        {
          label: "Release Transactions",
          path: "/home/finance/processes/release-transactions",
          roles: ["admin", "finance"],
        },
        {
          label: "Release Vouchers",
          path: "/home/finance/processes/release-vouchers",
          roles: ["admin", "finance"],
        },
        {
          label: "Post Transactions",
          path: "/home/finance/processes/post-transactions",
          roles: ["admin", "finance"],
        },
        {
          label: "Run Allocations",
          path: "/home/finance/processes/run-allocations",
          roles: ["admin", "finance"],
        },
        {
          label: "Generate Recurring Transactions",
          path: "/home/finance/processes/generate-recurring",
          roles: ["admin", "finance"],
        },
        {
          label: "Reclassify Transactions",
          path: "/home/finance/processes/reclassify-transactions",
          roles: ["admin", "finance"],
        },
        {
          label: "Import Consolidation Data",
          path: "/home/finance/processes/import-consolidation",
          roles: ["admin", "finance"],
        },
        {
          label: "Manage Financial Periods",
          path: "/home/finance/processes/manage-financial-periods",
          roles: ["admin", "finance"],
        },
        {
          label: "Recalculate Account History",
          path: "/home/finance/processes/recalculate-history",
          roles: ["admin", "finance"],
        },
      ],
      Budgets: [
        {
          label: "Budgets",
          path: "/home/finance/budgets",
          roles: ["admin", "finance"],
        },
        {
          label: "Release Budgets",
          path: "/home/finance/budgets/release",
          roles: ["admin", "finance"],
        },
        {
          label: "GL Budget Edit",
          path: "/home/finance/budgets/budget-edit",
          roles: ["admin", "finance"],
        },
      ],
      Inquiries: [
        {
          label: "Account Summary",
          path: "/home/finance/inquiries/account-summary",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account by Subaccount",
          path: "/home/finance/inquiries/by-subaccount",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account by Period",
          path: "/home/finance/inquiries/by-period",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account Details",
          path: "/home/finance/inquiries/account-details",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "GL Budget and Actual BI",
          path: "/home/finance/inquiries/budget-actual-bi",
          roles: ["admin", "finance", "viewer"],
        },
      ],
      Reports: [
        {
          label: "Trial Balance Summary",
          path: "/home/finance/reports/tb-summary",
          roles: ["admin"],
        },
        {
          label: "Trial Balance Detailed",
          path: "/home/finance/reports/tb-detailed",
          roles: ["admin"],
        },
        {
          label: "Transactions for Period",
          path: "/home/finance/reports/transactions-period",
          roles: ["admin"],
        },
        {
          label: "Transactions for Account",
          path: "/home/finance/reports/transactions-account",
          roles: ["admin"],
        },
        {
          label: "GL Edit Summary",
          path: "/home/finance/reports/gl-edit-summary",
          roles: ["admin"],
        },
        {
          label: "GL Edit Detailed",
          path: "/home/finance/reports/gl-edit-detailed",
          roles: ["admin"],
        },
        {
          label: "GL Account Distribution",
          path: "/home/finance/reports/account-distribution",
          roles: ["admin"],
        },
        {
          label: "GL Register",
          path: "/home/finance/reports/gl-register",
          roles: ["admin"],
        },
        {
          label: "GL Register Detailed",
          path: "/home/finance/reports/gl-register-detailed",
          roles: ["admin"],
        },
        {
          label: "GL Recurring Transactions",
          path: "/home/finance/reports/gl-recurring-transactions",
          roles: ["admin"],
        },
        {
          label: "GL Recurring Transactions Detailed",
          path: "/home/finance/reports/gl-recurring-transactions-detailed",
          roles: ["admin"],
        },
        {
          label: "GL Reversing Batches",
          path: "/home/finance/reports/gl-reversing-batches",
          roles: ["admin"],
        },
        {
          label: "General Ledger Details  ",
          path: "/home/finance/reports/gl-details",
          roles: ["admin"],
        },
      ],
      "Financial Statements": [
        {
          label: "CQ Standard BS - Comparative",
          path: "/home/finance/financial_statements/cq_standard_bs_comparative",
          roles: ["admin"],
        },
        {
          label: "CQ Departamental P&L - PTD",
          path: "/home/finance/financial_statements/cq_departamental_pl_ptd",
          roles: ["admin"],
        },
        {
          label: "CQ Standard Balance Sheet",
          path: "/home/finance/financial_statements/cq_standard_balance_sheet",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Comparative",
          path: "/home/finance/financial_statements/cq_standard_pl_comparative",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Conso",
          path: "/home/finance/financial_statements/cq_standard_pl_conso",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Cebu",
          path: "/home/finance/financial_statements/cq_standard_pl_cebu",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Manila",
          path: "/home/finance/financial_statements/cq_standard_pl_manila",
          roles: ["admin"],
        },
        {
          label: "CQ Departamental P&L - YTD",
          path: "/home/finance/financial_statements/cq_departamental_pl_ytd",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Monthly",
          path: "/home/finance/financial_statements/cq_standard_pl_monthly",
          roles: ["admin"],
        },
        {
          label: "CQ Product Line - Monthly",
          path: "/home/finance/financial_statements/cq_product_line_monthly",
          roles: ["admin"],
        },
        {
          label: "CQ Product Line - Comparative",
          path: "/home/finance/financial_statements/cq_product_line_comparative",
          roles: ["admin"],
        },
        {
          label: "CQ Standard BS - Monthly",
          path: "/home/finance/financial_statements/cq_standard_bs_monthly",
          roles: ["admin"],
        },
        {
          label: "CQ Standard P&L - Quarterly",
          path: "/home/finance/financial_statements/cq_standard_pl_quarterly",
          roles: ["admin"],
        },
        {
          label: "MHE - Budget vs Actual",
          path: "/home/finance/financial_statements/mhe_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "ISS - Budget vs Actual",
          path: "/home/finance/financial_statements/iss_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "PCS - Budget vs Actual",
          path: "/home/finance/financial_statements/pcs_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "CCS - Budget vs Actual",
          path: "/home/finance/financial_statements/ccs_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "PCC - Budget vs Actual",
          path: "/home/finance/financial_statements/pcc_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "HQR - Budget vs Actual",
          path: "/home/finance/financial_statements/hqr_budget_vs_actual",
          roles: ["admin"],
        },

        {
          label: "ENGG - Budget vs Actual",
          path: "/home/finance/financial_statements/engg_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "CEBU - Budget vs Actual",
          path: "/home/finance/financial_statements/cebu_budget_vs_actual",
          roles: ["admin"],
        },
        {
          label: "All Dept - Budget vs Actual",
          path: "/home/finance/financial_statements/all_dept_budget_vs_actual",
          roles: ["admin"],
        },
      ],
      Preferences: [
        {
          label: "General Ledger Preferences",
          path: "/home/finance/preferences/gl-prefs",
          roles: ["admin"],
        },
        {
          label: "Financial Year",
          path: "/home/finance/preferences/year",
          roles: ["admin"],
        },
        {
          label: "Ledgers",
          path: "/home/finance/preferences/ledgers",
          roles: ["admin"],
        },
        {
          label: "Voucher Entry Codes",
          path: "/home/finance/preferences/vouchers_entry_codes",
          roles: ["admin"],
        },
        {
          label: "Budget Configuration",
          path: "/home/finance/preferences/budget-config",
          roles: ["admin"],
        },
        {
          label: "Consolidation",
          path: "/home/finance/preferences/consolidation",
          roles: ["admin"],
        },
        {
          label: "Account Classes",
          path: "/home/finance/preferences/classes",
          roles: ["admin"],
        },
      ],
      Other: [
        {
          label: "Journal Voucher",
          path: "/home/other/journal-voucher",
          roles: ["admin"],
        },
      ],
    },
  },

  //until here
  {
    label: "Sales Order",
    icon: <MdNoteAdd />,
    roles: ["admin", "purchaser"],
    submenu: {
      Profiles: [
        {
          label: "Request",
          path: "/home/request",
          roles: ["admin", "purchaser"],
        },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
          roles: ["admin", "purchaser"],
        },
      ],
      Inquiries: [
        {
          label: "Vendor Details",
          path: "/home/purchases/details",
          roles: ["admin", "purchaser", "viewer"],
        },
      ],
    },
  },
  {
    label: "Payables",
    icon: <CiCircleMinus />,
    roles: ["admin", "accounting"],
    submenu: {
      Profiles: [
        {
          label: "Request",
          path: "/home/request",
          roles: ["admin", "accounting"],
        },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
          roles: ["admin", "accounting"],
        },
      ],
      Inquiries: [
        {
          label: "Vendor Details",
          path: "/home/purchases/details",
          roles: ["admin", "accounting", "viewer"],
        },
      ],
    },
  },
  {
    label: "Receivables",
    icon: <CiCirclePlus />,
    roles: ["admin", "accounting"],
    submenu: {
      Profiles: [
        {
          label: "Request",
          path: "/home/request",
          roles: ["admin", "accounting"],
        },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
          roles: ["admin", "accounting"],
        },
      ],
      Inquiries: [
        {
          label: "Vendor Details",
          path: "/home/purchases/details",
          roles: ["admin", "accounting", "viewer"],
        },
      ],
    },
  },
  {
    label: "Purchases",
    icon: <MdShoppingCart />,
    roles: ["admin", "finance"],
    submenu: {
      Profiles: [
        {
          label: "Request",
          path: "/home/request",
          roles: ["admin", "finance"],
        },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
          roles: ["admin", "purchasinghead", "purchaser"],
        },
      ],
      Inquiries: [
        {
          label: "Vendor Details",
          path: "/home/purchases/details",
          roles: ["admin", "purchasinghead", "viewer"],
        },
      ],
      Preferences: [
        {
          label: "Item Class",
          path: "/home/inventory/item_class",
          roles: ["admin", "inventory"],
        },
        {
          label: "New Purchase Request",
          path: "/home/purchases/create_request",
          roles: ["admin", "purchaser"],
        },
      ],
    },
  },
  {
    label: "Inventory",
    icon: <MdInventory />,
    roles: ["admin", "inventory"],
    submenu: {
      Profiles: [
        {
          label: "Master Financial Calendar",
          path: "/home/finance/calendar",
          roles: ["admin", "finance"],
        },
        {
          label: "Recurring Transactions",
          path: "/home/finance/recurring",
          roles: ["admin", "finance"],
        },
        {
          label: "Chart of Accounts",
          path: "/home/finance/accounts",
          roles: ["admin", "finance"],
        },
        {
          label: "Subaccounts",
          path: "/home/finance/subaccounts",
          roles: ["admin", "finance"],
        },
      ],
      Processes: [
        {
          label: "Manage Financial Periods",
          path: "/home/finance/periods",
          roles: ["admin", "finance"],
        },
        {
          label: "Validate Account History",
          path: "/home/finance/history",
          roles: ["admin", "finance"],
        },
      ],
      Budgets: [
        {
          label: "Budgets",
          path: "/home/finance/budgets",
          roles: ["admin", "finance"],
        },
        {
          label: "GL Budget Edit",
          path: "/home/finance/budget-edit",
          roles: ["admin", "finance"],
        },
      ],
      Inquiries: [
        {
          label: "Account Summary",
          path: "/home/finance/summary",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account by Subaccount",
          path: "/home/finance/by-subaccount",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account by Period",
          path: "/home/finance/by-period",
          roles: ["admin", "finance", "viewer"],
        },
        {
          label: "Account Details",
          path: "/home/finance/details",
          roles: ["admin", "finance", "viewer"],
        },
      ],
      Preferences: [
        {
          label: "General Ledger Preferences",
          path: "/home/finance/gl-prefs",
          roles: ["admin"],
        },
        {
          label: "Financial Year",
          path: "/home/finance/year",
          roles: ["admin"],
        },
        { label: "Ledgers", path: "/home/finance/ledgers", roles: ["admin"] },
        {
          label: "Voucher Entry Codes",
          path: "/home/finance/vouchers",
          roles: ["admin"],
        },
        {
          label: "Budget Configuration",
          path: "/home/finance/budget-config",
          roles: ["admin"],
        },
        {
          label: "Consolidation",
          path: "/home/finance/consolidation",
          roles: ["admin"],
        },
        {
          label: "Account Classes",
          path: "/home/finance/classes",
          roles: ["admin"],
        },
      ],
    },
  },
  {
    label: "Reports",
    icon: <MdReport />,
    path: "/home/reports",
    roles: ["admin", "viewer", "finance"],
  },
  {
    label: "Settings",
    icon: <MdSettings />,
    path: "/home/settings",
    roles: ["admin"],
  },
];

export const DUMMY_ITEM_CLASSES = [
  {
    classID: "MHE",
    description: "Material Handling Equipment",
    stockItem: true,
    allowNegativeQty: true,
    itemType: "Inventory",
    valuationMethod: "Standard",
    planningMethod: "Inventory Replenishment",
    taxCategory: "IMPGOODS",
    postingClass: "MHE-POST",
    lotSerialClass: "",
    priceClass: "",
    availabilityCalculation: "",
    countryOrigin: "",
    undershiThreshold: 0,
    ownershipThreshold: 0,
    baseUnit: "PIECE",
    salesUnit: "PIECE",
    purchaseUnit: "PIECE",
  },
  {
    classID: "ELC",
    description: "Electrical Components",
    stockItem: true,
    allownNegativeQty: true,
    itemType: "Inventory",
    valuationMethod: "FIFO",
    planningMethod: "Min/Max",
    taxCategory: "ELECTAX",
    postingClass: "ELC-POST",
    postCostToExpenses: "Purchases",
    lotSerialClass: "LOT-ELC",
    priceClass: "STANDARD",
    availabilityCalculation: "On Hand",
    countryOrigin: "PH",
    undershiThreshold: 5,
    overshipThreshold: 10,
    baseUnit: "PCS",
    salesUnit: "PCS",
    purchaseUnit: "BOX",
  },
  {
    classID: "CNS",
    description: "Construction Supplies",
    stockItem: true,
    allownNegativeQty: false,
    itemType: "Non-Inventory",
    valuationMethod: "Moving Average",
    planningMethod: "Reorder Point",
    taxCategory: "CIVIL",
    postingClass: "CNS-POST",
    lotSerialClass: "LOT-CNS",
    priceClass: "BULK",
    availabilityCalculation: "Projected",
    countryOrigin: "CN",
    undershiThreshold: 2,
    overshipThreshold: 15,
    baseUnit: "BAG",
    salesUnit: "BAG",
    purchaseUnit: "PALLET",
  },
  {
    classID: "OFF",
    description: "Office Supplies",
    stockItem: false,
    allownNegativeQty: true,
    itemType: "Service",
    valuationMethod: "None",
    planningMethod: "Manual",
    taxCategory: "SERVICES",
    postingClass: "OFF-POST",
    lotSerialClass: "",
    priceClass: "",
    availabilityCalculation: "None",
    countryOrigin: "",
    undershiThreshold: 0,
    overshipThreshold: 0,
    baseUnit: "SET",
    salesUnit: "SET",
    purchaseUnit: "SET",
  },
  {
    classID: "ITM",
    description: "IT Equipment",
    stockItem: true,
    allownNegativeQty: false,
    itemType: "Inventory",
    valuationMethod: "Standard",
    planningMethod: "Forecast",
    taxCategory: "ELECIMP",
    postingClass: "ITM-POST",
    lotSerialClass: "SERIAL-IT",
    priceClass: "TECH",
    availabilityCalculation: "Available for Sale",
    countryOrigin: "US",
    undershiThreshold: 1,
    overshipThreshold: 5,
    baseUnit: "UNIT",
    salesUnit: "UNIT",
    purchaseUnit: "BOX",
  },
];

export const DUMMY_ITEMS = [
  {
    inventory: "Item001232323",
    itemclass: "MHE-SPR-LND asasdasd",
    subitem: "A1",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 20,
    description: "Paper A4 axsasaassaasdassdasdasdadssdasadasdsasadsadsda",
    uom: "Ream",
    orderQty: 1,
    unitCost: 100,
    extVendorCost: 100,
    vendor: "",
    location: "",
    vendorName: "",
    vendorRef: "",
    vendorDescription: "",
    alternateID: "",
    requiredDate: "2025-06-11",
    promisedDate: "2025-06-11",
    issueStatus: "Open",
  },

  {
    inventory: "Item002",
    itemclass: "MHE-SPR-LND",
    subitem: "B2",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Pen Blue",
    uom: "Box",
    orderQty: 2,
    unitCost: 50,
    extVendorCost: 1200,
    location: "",
    vendor: "",
  },
  {
    inventory: "Item003",
    itemclass: "MHE-SPR-LND",
    subitem: "C3",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Notebook",
    uom: "Piece",
    orderQty: 5,
    unitCost: 20,
    extVendorCost: 1300,
    location: "",
    vendor: "",
  },
  {
    inventory: "Item004",
    itemclass: "MHE-SPR-LND",
    subitem: "C3",
    itemstatus: "Active",
    type: "Finishe Goods",
    baseunit: "PIECE",
    salesunit: "PIECE",
    purchaseunit: "PIECE",
    defaultprice: 0,
    description: "Notebook",
    uom: "Piece",
    orderQty: 5,
    unitCost: 20,
    extVendorCost: 300,
    location: "",
    vendor: "",
  },
];

export const requests = [
  {
    ref: "RQ00009575",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PENETRATING OIL - WD40",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "PENETRATING OIL - WD40PENETRATING OIL - WD40",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "PENETRATING OIL - WD40",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "COTTON RAGS",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RRQ0000957532",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PM Materials for JIA2 - RC5500 / 1A430954",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item001232323",
        itemclass: "MHE-SPR-LND asasdasd",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 20,
        description: "Paper A4 axsasaassaasdassdasdasdadssdasadasdsasadsadsda",
        uom: "Ream",
        orderQty: 1,
        unitCost: 100,
        extVendorCost: 100,
        vendor: "",
        location: "",
        vendorName: "",
        vendorRef: "",
        vendorDescription: "",
        alternateID: "",
        requiredDate: "2025-06-11",
        promisedDate: "2025-06-11",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RQ000095754",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RQ000095755",
    status: "Closed",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "CONSUMABLES",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Rental of Boomtruck for Supersail Cebu",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },

      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
    ],
  },

  {
    ref: "RQ000095756",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Internal Rental for Crystal Cold for R20 C2Y115M01362",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RQ000095757",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RQ000095758",
    status: "Closed",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "PM Materials for JIA2 - RC5500 / 1A430954",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "PMM-WD40MTLS",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "PENETRATING OIL - WD40",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item003",
        itemclass: "MHE-SPR-LND",
        subitem: "C3",
        itemstatus: "Active",
        type: "Finishe Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 0,
        description: "Notebook",
        uom: "Piece",
        orderQty: 5,
        unitCost: 20,
        extVendorCost: 1300,
        location: "",
        vendor: "",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RQ000095759",
    status: "Closed",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Consumables for SHIN-ETSU Project",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RQ000095752",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Purchase of Linde for Royal Cargo ADY6113 SN: 20240409V154",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Rental of Truck at ROMBE Project (Pull-out)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RQ000095751",
    status: "Open",
    priority: "Normal",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Trucking for the delivery of Visipro to Doxo Polyland",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RQ0000957512",
    status: "Closed",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Materials for SHIN-ETSU Project",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  {
    ref: "RQ0000957534",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Purchase of Linde for Royal Cargo ADY6113 SN: 20240409V154",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },

  {
    ref: "RQ0000957512",
    status: "Open",
    priority: "High",
    date: "6/11/2025",
    requestClass: "RNTLPRTSRQ",
    requestedBy: "BA00000258",
    location: "MAIN",
    department: "MHESER",
    description: "Advance Purchase of Parts for Bounty R16SHD / C2Y115L01599",
    extCost: "0.00",
    icon: "description",
    statusIcon: "chevron_right",
    notes: true,
    items: [
      {
        inventory: "Item001232323323",
        itemclass: "MHE-SPR-LND edited",
        subitem: "A1",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 25,
        description: "Paper A4 (edited)",
        uom: "Ream",
        orderQty: 2,
        unitCost: 105,
        extVendorCost: 210,
        vendor: "VEND001",
        location: "WH1",
        vendorName: "VendorCorp",
        vendorRef: "VC001",
        vendorDescription: "Bulk paper supply",
        alternateID: "ALT-PAPER-001",
        requiredDate: "2025-06-15",
        promisedDate: "2025-06-20",
        issueStatus: "Open",
      },
      {
        inventory: "Item002",
        itemclass: "MHE-SPR-LND",
        subitem: "B2",
        itemstatus: "Active",
        type: "Finished Goods",
        baseunit: "PIECE",
        salesunit: "PIECE",
        purchaseunit: "PIECE",
        defaultprice: 10,
        description: "Pen Blue (edited)",
        uom: "Box",
        orderQty: 3,
        unitCost: 40,
        extVendorCost: 120,
        vendor: "VEND002",
        location: "WH2",
        vendorName: "InkExpress",
        vendorRef: "INK001",
        vendorDescription: "Office pens",
        alternateID: "ALT-PEN-002",
        requiredDate: "2025-06-16",
        promisedDate: "2025-06-21",
        issueStatus: "Open",
      },
    ],
  },
  // You can keep the rest of your request objects the same or add `items` to any of them as needed.
];
